# Generated by Django 5.1.7 on 2025-03-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_decription_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(default=1, max_length=200, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
