# Generated by Django 5.1.7 on 2025-03-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='image.png', upload_to='image/%Y', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
