# Generated by Django 5.1.7 on 2025-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_number',
            field=models.IntegerField(default=0, max_length=1000, verbose_name='Количество комментариев'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.FloatField(default=0, max_length=5, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
