# Generated by Django 5.1.7 on 2025-03-23 19:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comments_time_alter_comments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=datetime.time(22, 46, 44, 693499), verbose_name='Время публикации комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments_number',
            field=models.IntegerField(verbose_name='Количество комментариев'),
        ),
    ]
