# Generated by Django 5.1.7 on 2025-03-23 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comments_post_alter_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=datetime.time(22, 52, 38, 805750), verbose_name='Время публикации комментария'),
        ),
    ]
