# Generated by Django 5.1.7 on 2025-03-23 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=datetime.time(22, 58, 24, 671564), verbose_name='Время публикации комментария'),
        ),
    ]
