# Generated by Django 5.1.7 on 2025-03-23 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_comments_date_alter_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=datetime.time(0, 19, 13, 955077), verbose_name='Время публикации комментария'),
        ),
    ]
