# Generated by Django 5.1.7 on 2025-03-29 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 29), verbose_name='Дата публикации комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=datetime.time(13, 9, 55, 760508), verbose_name='Время публикации комментария'),
        ),
    ]
