# Generated by Django 5.1.7 on 2025-03-23 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=datetime.time(0, 49, 6, 716286), verbose_name='Время публикации комментария'),
        ),
    ]
