# Generated by Django 5.1.7 on 2025-03-29 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_comments_date_alter_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=datetime.time(13, 32, 34, 507039), verbose_name='Время публикации комментария'),
        ),
    ]
