# Generated by Django 5.1.7 on 2025-03-29 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=datetime.time(13, 38, 46, 624896), verbose_name='Время публикации комментария'),
        ),
    ]
