# Generated by Django 5.1.7 on 2025-03-29 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=datetime.time(13, 41, 9, 539497), verbose_name='Время публикации комментария'),
        ),
    ]
