# Generated by Django 5.1.7 on 2025-03-29 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=datetime.time(15, 51, 13, 614113), verbose_name='Время публикации комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='admin', max_length=100, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments_number',
            field=models.IntegerField(editable=False, verbose_name='Количество комментариев'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 29, 12, 51, 13, 614113, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='image/%Y', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.FloatField(editable=False, max_length=5, verbose_name='Рейтинг'),
        ),
    ]
