# Generated by Django 5.1.7 on 2025-03-29 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_comments_time_alter_post_date_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=datetime.time(15, 57, 5, 339248), verbose_name='Время публикации комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 29, 12, 57, 5, 339248, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='default.png', upload_to='image/%Y', verbose_name='Изображение'),
        ),
    ]
