# Generated by Django 5.1.7 on 2025-04-02 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_comments_time_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.date(2025, 4, 2), verbose_name='Дата публикации комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=datetime.time(17, 26, 34, 832243), verbose_name='Время публикации комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 2, 14, 26, 34, 831090, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
